---
- name: Install npm on web servers 
  hosts: webservers
  become: yes  # Use sudo privileges on remote servers

  tasks:
    - name: Ensure Node.js is present (Recommended)
      homebrew: 
        name: node
        state: present

    - name: Install npm 
      # npm mostly comes with Node.js; check if separate installation needed
      homebrew:
        name: npm
        state: present 
