---
- name: Install and start a Node.js application
  hosts: webservers
  become: yes
  tasks:
    - name: Install Git
      package:
        name: git
        state: present

    - name: Clone the repository
      git:
        repo: https://github.com/UlugbekSattarov/FSI2Final/tree/main/Q1
        dest: /home/user/node_app

    - name: Install dependencies
      shell: npm install
      args:
        chdir: /home/user/node_app

    - name: Start the application
      shell: npm start &
      args:
        chdir: /home/user/node_app
